// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ZQXQzMSJucHrG4csaXV5VPUdnwt7F3c',
    appId: '1:604999144229:android:4ac2e3dd6aa698f02b40cc',
    messagingSenderId: '604999144229',
    projectId: 'chapapp-22e3d',
    storageBucket: 'chapapp-22e3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJNNcXB07mdASE-Xi9xapGqQtZRICGpCg',
    appId: '1:604999144229:ios:85b026d7c7c8159f2b40cc',
    messagingSenderId: '604999144229',
    projectId: 'chapapp-22e3d',
    storageBucket: 'chapapp-22e3d.appspot.com',
    iosClientId: '604999144229-dqpc4hl187eui318vnu4pll52hv6ju3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );
}
